from abc import ABC, abstractmethod
from typing import List, Optional
from domain.entities import Usuario, Servicio, Evidencia, Calificacion

class UserRepository(ABC):
    @abstractmethod
    def get_by_id(self, user_id: int) -> Optional[Usuario]: ...
    @abstractmethod
    def get_by_email(self, email: str) -> Optional[Usuario]: ...
    @abstractmethod
    def create(self, user: Usuario) -> Usuario: ...
    @abstractmethod
    def update(self, user: Usuario) -> Usuario: ...
    @abstractmethod
    def list_by_role(self, role: str) -> List[Usuario]: ...
    @abstractmethod
    def list_all(self) -> List[Usuario]: ...

class ServiceRepository(ABC):
    @abstractmethod
    def create(self, service: Servicio) -> Servicio: ...
    @abstractmethod
    def get_by_id(self, service_id: int) -> Optional[Servicio]: ...
    @abstractmethod
    def list_by_client(self, client_id: int) -> List[Servicio]: ...
    @abstractmethod
    def list_by_recycler(self, reciclador_id: int) -> List[Servicio]: ...
    @abstractmethod
    def list_all(self) -> List[Servicio]: ...
    @abstractmethod
    def update(self, service: Servicio) -> Servicio: ...

class EvidenceRepository(ABC):
    @abstractmethod
    def create(self, evidence: Evidencia) -> Evidencia: ...
    @abstractmethod
    def get_by_service(self, service_id: int) -> Optional[Evidencia]: ...

class RatingRepository(ABC):
    @abstractmethod
    def create(self, rating: Calificacion) -> Calificacion: ...
    @abstractmethod
    def get_by_service(self, service_id: int) -> Optional[Calificacion]: ...
    @abstractmethod
    def list_by_recycler(self, reciclador_id: int) -> List[Calificacion]: ...
    @abstractmethod
    def list_all(self) -> List[Calificacion]: ...